---
- name: install php
  import_role:
    name: php

- name: install member.lghs.be vhost
  import_role:
    name: reverse-proxy-unix
  vars:
    vhost: members.lghs.be
    socket: /var/run/php/php7.2-fpm.sock
