---
- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php

- name: Install composer
  command: php /tmp/composer-setup.php --install-dir=/usr/bin --filename=composer

- name: Update to latest composer version
  command: composer selfupdate
