---
- name: add php apt key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg

- name: add php apt source
  apt_repository:
    repo: 'deb https://packages.sury.org/php/ stretch main'

- name: install php packages
  apt:
    pkg: "{{ item }}"
    state: present
    update-cache: yes
  with_items:
    - php7.2
    - php7.2-cli
    - php7.2-fpm
    - php7.2-curl
    - php7.2-mbstring
    - php7.2-opcache
    - php7.2-pgsql
    - php7.2-xml
    - php7.2-zip
