---
- name: add php apt key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg

- name: add php apt source
  apt_repository:
    repo: 'deb https://packages.sury.org/php/ stretch main'

- name: install php packages
  apt:
    pkg:
      - php7.2
      - php7.2-cli
      - php7.2-fpm
      - php7.2-curl
      - php7.2-mbstring
      - php7.2-opcache
      - php7.2-pgsql
      - php7.2-xml
      - php7.2-zip
    state: present
    update-cache: yes


# if nginx is installed, make sure it can talk to php-fpm
- name: Determine available groups
  getent:
    database: passwd

- name: Add additional groups to user
  user: name="nginx" groups="www-data" append=yes
  when: '"nginx" in getent_passwd'
