---
- hosts: all
  become: yes
  roles:
    - common

- hosts: web
  become: yes
  roles:
    - web-server

- hosts: database
  become: yes
  roles:
    - database-server

- hosts: candy
  become: yes
  roles:
    - rocketchat

- hosts: roger
  become: yes
  roles:
    - members.lghs.be
    # - lghs.be
